services:
  - type: web
    name: dwell-timer
    env: static
    buildCommand: npm install --include=dev && npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: CI 
        value: false
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache