services:
  - type: web
    name: dwell-timer
    env: static
    buildCommand: npm install -g react-scripts && CI=false npm run build
    staticPublishPath: ./build
    envVars:
      - key: NODE_VERSION
        value: 18